import Link from "next/link";
import { LogoWordmark } from "@/components/logo-mark";

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-16">
      <Link href="/">
        <LogoWordmark size={28} />
      </Link>
      <h1 className="mt-6 text-2xl font-semibold tracking-tight">Privacy Policy</h1>
      <p className="mt-2 text-sm text-muted-foreground">Last updated 13 September 2026.</p>

      <div className="mt-8 space-y-6 text-sm leading-relaxed text-muted-foreground">
        <section>
          <h2 className="text-base font-medium text-foreground">1. What we collect</h2>
          <p className="mt-2">
            Account details you provide (name, email), authentication data from OAuth providers you choose to sign
            in with, SSH public keys you add, and usage data generated by using the service — rentals, billing
            events, and support requests. We never store your SSH private key; only the public key you paste.
          </p>
        </section>
        <section>
          <h2 className="text-base font-medium text-foreground">2. How we use it</h2>
          <p className="mt-2">
            To provision and bill GPU rentals, authenticate you, provide support, and improve the service. Payment
            is processed by Stripe — we don't store your card details ourselves.
          </p>
        </section>
        <section>
          <h2 className="text-base font-medium text-foreground">3. What we don't do</h2>
          <p className="mt-2">
            We don't sell your personal data. We don't access the contents of a running rental instance except as
            needed to operate, secure, or troubleshoot the service, or where required by law.
          </p>
        </section>
        <section>
          <h2 className="text-base font-medium text-foreground">4. Sharing</h2>
          <p className="mt-2">
            We share data with infrastructure and payment providers strictly as needed to operate the service (for
            example, our GPU hosting provider and Stripe), and with authorities where legally required.
          </p>
        </section>
        <section>
          <h2 className="text-base font-medium text-foreground">5. Retention</h2>
          <p className="mt-2">
            Account and billing records are kept for as long as your account is active and as needed to meet legal
            and accounting obligations afterward. Data on a terminated GPU instance is deleted with the instance.
          </p>
        </section>
        <section>
          <h2 className="text-base font-medium text-foreground">6. Your rights</h2>
          <p className="mt-2">
            You can update your profile from Account settings, or request access to, correction of, or deletion of
            your personal data by contacting us.
          </p>
        </section>
        <section>
          <h2 className="text-base font-medium text-foreground">7. Contact</h2>
          <p className="mt-2">
            Questions about this policy can be sent to{" "}
            <a href="mailto:privacy@taskflow.web-agent.org" className="text-primary hover:underline">
              privacy@taskflow.web-agent.org
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
